services:
  bookmarkly:
    build: .
    ports:
      - "8888:80"
    volumes:
      - bookmarkly_data:/var/www/html/bookmarkly/data
    environment:
      - BOOKMARKLY_VERSION=1.5
    restart: unless-stopped

volumes:
  bookmarkly_data:
    driver: local

