services:
  bookmarkly:
    image: ghcr.io/r0gger/bookmarkly:latest
    ports:
      - "80:80"
    volumes:
      - bookmarkly_data:/var/www/html/bookmarkly/data
    environment:
      - BOOKMARKLY_VERSION=1.6
    restart: unless-stopped

volumes:
  bookmarkly_data:
    driver: local
